# Generated by Django 6.0 on 2025-12-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('isin_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('bse_symbol', models.CharField(max_length=6, unique=True)),
                ('nse_symbol', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('last_price', models.FloatField()),
                ('open', models.FloatField()),
                ('day_high', models.FloatField()),
                ('day_low', models.FloatField()),
                ('previous_close', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markets.stocks')),
            ],
            options={
                'db_table': 'StockPrices',
                'unique_together': {('stock', 'datetime')},
            },
        ),
    ]
