# Generated by Django 6.0 on 2025-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='bse_symbol',
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='nse_symbol',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
