# Generated by Django 6.0 on 2025-12-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=50),
        ),
    ]
