# Generated by Django 6.0 on 2025-12-04 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useractivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
